version: '3'

services:
  postgresql2:
    container_name: postgresql2
    image: postgres:14.2-alpine
    env_file:
        - .env
    ports:
        - "5432:5432"
    volumes:
        - "postgres_data:/var/lib/postgresql/data"
        - "./sql/:/docker-entrypoint-initdb.d/"

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
    driver: local
